import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import JsBarcode from 'jsbarcode';
import QRCode from 'qrcode';
import './styles.css';

const copy = {
  ar:{title:'استوديو الباركود',subtitle:'أنشئ باركوداً واضحاً وجاهزاً للطباعة خلال ثوانٍ',language:'اللغة',dark:'الوضع الليلي',paper:'حجم الملصق',width:'العرض (مم)',height:'الارتفاع (مم)',font:'حجم الخط',data:'بيانات المنتج',code:'رقم الباركود',name:'اسم المنتج',price:'السعر',currency:'العملة',position:'مكان البيانات',top:'أعلى الباركود',bottom:'أسفل الباركود',labelFont:'حجم بيانات المنتج',placeholder:'اكتب رقم المنتج هنا...',namePlaceholder:'مثال: قهوة عربية 250 غرام',type:'نوع الباركود',numeric:'أرقام معروضة',plain:'بدون أرقام',qr:'رمز QR',generate:'إنشاء الباركود',save:'حفظ الصورة',print:'طباعة',copies:'عدد النسخ',preview:'المعاينة',ready:'جاهز للمعاينة',hint:'يمكنك استخدام العربية والإنجليزية معاً',saved:'تم حفظ الصورة بنجاح',empty:'أدخل رقم الباركود أولاً',printFail:'تعذر بدء الطباعة',calibration:'معايرة الطباعة',marginTop:'الهامش العلوي',marginSide:'الهامش الجانبي',gap:'المسافة بين الملصقات',scale:'مقياس الطباعة',history:'السجل الأخير',search:'ابحث بالاسم أو الرقم...',noHistory:'لا توجد باركودات محفوظة بعد',edit:'تعديل',reprint:'إعادة الطباعة',remove:'حذف',camera:'مسح بالكاميرا',close:'إغلاق',},
  en:{title:'Barcode Studio',subtitle:'Create a clear, print-ready barcode in seconds',language:'Language',dark:'Dark mode',paper:'Label size',width:'Width (mm)',height:'Height (mm)',font:'Font size',data:'Product details',code:'Barcode value',name:'Product name',price:'Price',currency:'Currency',position:'Details position',top:'Above barcode',bottom:'Below barcode',labelFont:'Details font size',placeholder:'Enter product number...',namePlaceholder:'Example: Arabica Coffee 250g',type:'Barcode type',numeric:'Numbers shown',plain:'No numbers',qr:'QR code',generate:'Create barcode',save:'Save image',print:'Print',copies:'Copies',preview:'Preview',ready:'Ready for preview',hint:'Arabic and English text are supported',saved:'Image saved successfully',empty:'Enter a barcode value first',printFail:'Could not start printing',calibration:'Print calibration',marginTop:'Top margin',marginSide:'Side margin',gap:'Label spacing',scale:'Print scale',history:'Recent barcodes',search:'Search by name or number...',noHistory:'No saved barcodes yet',edit:'Edit',reprint:'Reprint',remove:'Delete',camera:'Scan with camera',close:'Close',},
  fr:{title:'Studio Code-barres',subtitle:'Créez un code-barres prêt à imprimer',language:'Langue',dark:'Mode sombre',paper:'Taille de l’étiquette',width:'Largeur (mm)',height:'Hauteur (mm)',font:'Taille du texte',data:'Détails du produit',code:'Valeur du code',name:'Nom du produit',price:'Prix',currency:'Devise',position:'Position des détails',top:'Au-dessus',bottom:'Au-dessous',labelFont:'Taille des détails',placeholder:'Saisissez le numéro...',namePlaceholder:'Exemple : Café Arabica 250g',type:'Type de code',numeric:'Chiffres affichés',plain:'Sans chiffres',qr:'Code QR',generate:'Créer le code',save:'Enregistrer',print:'Imprimer',copies:'Copies',preview:'Aperçu',ready:'Prêt pour l’aperçu',hint:'L’arabe et l’anglais sont pris en charge',saved:'Image enregistrée',empty:'Saisissez d’abord une valeur',printFail:'Impression impossible',calibration:'Calibrage d’impression',marginTop:'Marge supérieure',marginSide:'Marge latérale',gap:'Espacement',scale:'Échelle d’impression',history:'Historique récent',search:'Rechercher par nom ou numéro...',noHistory:'Aucun code enregistré',edit:'Modifier',reprint:'Réimprimer',remove:'Supprimer',camera:'Scanner avec caméra',close:'Fermer',}
};
const defaults={font:16,value:'123456789012',name:'قهوة عربية 250 غرام',price:'12.50',currency:'د.ع',contentMode:'barcode',type:'numeric',copies:1};

function App(){
 const [lang,setLang]=useState('ar'),[dark,setDark]=useState(false); const t=copy[lang]; const rtl=lang==='ar';
 const [form,setForm]=useState({...defaults}); const [image,setImage]=useState(''); const [search,setSearch]=useState(''); const canvasRef=useRef(null);
 const [history,setHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem('barcode-history')||'[]')}catch{return []}});
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=rtl?'rtl':'ltr'},[lang,rtl]);
 const set=(key,val)=>setForm(f=>({...f,[key]:val}));
 const modeLabel=form.contentMode==='barcode'?(lang==='ar'?'باركود فقط':lang==='fr'?'Code seul':'Barcode only'):form.contentMode==='price'?(lang==='ar'?'باركود مع سعر':lang==='fr'?'Code + prix':'Barcode + price'):(lang==='ar'?'باركود مع سعر واسم المنتج':lang==='fr'?'Code + prix + nom':'Barcode + price + product name');
 const makeCanvas=async()=>{const f=form,canvas=canvasRef.current,pxW=680,baseH=300;canvas.width=pxW;canvas.height=baseH;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,pxW,baseH);ctx.textAlign='center';const details=f.contentMode==='barcode'?'':f.contentMode==='price'?`${f.price} ${f.currency}`:`${f.name||''}  •  ${f.price} ${f.currency}`;ctx.font=`${Math.max(12,Number(f.font))}px Cairo, Arial`;ctx.fillStyle='#111827';if(details)ctx.fillText(details,pxW/2,30);const y=details?34:0;if(f.type==='qr'){await QRCode.toCanvas(canvas,f.value,{width:220,margin:2,color:{dark:'#111827',light:'#ffffff'}});if(details)ctx.fillText(details,pxW/2,baseH-12)}else{JsBarcode(canvas,f.value,{format:'CODE128',width:3,height:details?170:205,displayValue:f.type==='numeric',fontSize:Number(f.font),margin:12,background:'#ffffff',lineColor:'#111827',textMargin:8});if(details) {ctx.font=`${Math.max(12,Number(f.font))}px Cairo, Arial`;ctx.fillText(details,pxW/2,baseH-12)}}return canvas.toDataURL('image/png')};
 const generate=async(saveHistory=true)=>{if(!form.value.trim()){alert(t.empty);return}const data=await makeCanvas();setImage(data);if(saveHistory){const item={...form,id:Date.now(),created:new Date().toLocaleString()};const next=[item,...history.filter(x=>x.value!==form.value||x.name!==form.name)].slice(0,30);setHistory(next);localStorage.setItem('barcode-history',JSON.stringify(next))}};
 useEffect(()=>{generate(false)},[]);useEffect(()=>{const timer=setTimeout(()=>generate(false),120);return()=>clearTimeout(timer)},[form.type,form.value,form.name,form.price,form.currency,form.contentMode,form.font]);
 const save=async()=>{if(!image)return;if(window.barcodeAPI)await window.barcodeAPI.saveFile({data:image,defaultPath:`${form.name||'barcode'}.png`,filters:[{name:'PNG Image',extensions:['png']}]});else{const a=document.createElement('a');a.href=image;a.download='barcode.png';a.click()}alert(t.saved)};
 const print=async()=>{if(window.barcodeAPI){const r=await window.barcodeAPI.print(Number(form.copies)||1);if(!r.success)alert(t.printFail)}else window.print()};
 const filtered=useMemo(()=>history.filter(x=>`${x.name} ${x.value}`.toLowerCase().includes(search.toLowerCase())),[history,search]);
 const load=(item)=>{setForm({...defaults,...item});setTimeout(()=>generate(false),0)};const remove=(id)=>{const next=history.filter(x=>x.id!==id);setHistory(next);localStorage.setItem('barcode-history',JSON.stringify(next))};
 return <div className={`app ${dark?'dark':''}`}>
  <header><div className="brand"><div className="brand-mark">▥</div><div><h1>{t.title}</h1><p>{t.subtitle}</p></div></div><div className="header-actions"><label className="language">{t.language}<select value={lang} onChange={e=>setLang(e.target.value)}><option value="ar">العربية</option><option value="en">English</option><option value="fr">Français</option></select></label><button className="theme" onClick={()=>setDark(!dark)}>{dark?'☀':'◐'} {t.dark}</button></div></header>
  <main><section className="panel controls"><div className="section-title"><span className="step">1</span><div><h2>{t.data}</h2><p>{t.hint}</p></div></div><label className="field-label">{t.code}<input value={form.value} onChange={e=>set('value',e.target.value)} placeholder={t.placeholder} dir="auto"/></label><div className="row product-row"><label>{t.name}<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder={t.namePlaceholder} dir="auto"/></label><label>{t.price}<input value={form.price} onChange={e=>set('price',e.target.value)}/></label><label>{t.currency}<select value={form.currency} onChange={e=>set('currency',e.target.value)}><option>د.ع</option><option>$</option><option>€</option><option>ر.س</option><option>د.إ</option><option>£</option></select></label></div><div className="row"><label>{t.font}<select value={form.font} onChange={e=>set('font',e.target.value)}><option value="12">12 px</option><option value="16">16 px</option><option value="20">20 px</option><option value="24">24 px</option></select></label><label>{t.copies}<input type="number" min="1" max="999" value={form.copies} onChange={e=>set('copies',Math.max(1,Math.min(999,Number(e.target.value)||1)))}/></label></div>
   <div className="section-title second"><span className="step">2</span><div><h2>{lang==='ar'?'محتوى الملصق':lang==='fr'?'Contenu de l’étiquette':'Label content'}</h2></div></div><div className="content-options"><button className={form.contentMode==='barcode'?'selected':''} onClick={()=>set('contentMode','barcode')}>{lang==='ar'?'باركود فقط':lang==='fr'?'Code seul':'Barcode only'}</button><button className={form.contentMode==='price'?'selected':''} onClick={()=>set('contentMode','price')}>{lang==='ar'?'باركود مع سعر':lang==='fr'?'Code + prix':'Barcode + price'}</button><button className={form.contentMode==='priceName'?'selected':''} onClick={()=>set('contentMode','priceName')}>{lang==='ar'?'باركود مع سعر واسم المنتج':lang==='fr'?'Code + prix + nom':'Barcode + price + name'}</button></div>
   <div className="section-title second"><span className="step">3</span><div><h2>{t.type}</h2></div></div><div className="types"><button className={form.type==='numeric'?'selected':''} onClick={()=>set('type','numeric')}><span className="type-icon">▥</span><b>{t.numeric}</b><small>CODE 128</small></button><button className={form.type==='plain'?'selected':''} onClick={()=>set('type','plain')}><span className="type-icon">▥</span><b>{t.plain}</b><small>CODE 128</small></button><button className={form.type==='qr'?'selected':''} onClick={()=>set('type','qr')}><span className="type-icon qr-icon">▦</span><b>{t.qr}</b><small>QR</small></button></div><button className="generate" onClick={()=>generate()}>✦ {t.generate}</button>
  </section><section className="panel preview-panel"><div className="preview-heading"><div><h2>{t.preview}</h2><p>{modeLabel}</p></div><span className="status">● {t.ready}</span></div><div className="preview-box">{image?<img src={image} alt="barcode preview"/>:<div className="empty">▥</div>}</div><div className="preview-meta"><span>PNG · {modeLabel}</span><span>{form.type==='qr'?'QR CODE':'CODE 128'}</span></div><div className="actions"><button className="outline" onClick={save}>⇩ {t.save}</button><button className="dark-button" onClick={()=>print()}>⎙ {t.print}</button></div><canvas ref={canvasRef} className="hidden-canvas"/></section>
  <section className="panel history-panel"><div className="history-head"><h2>{t.history}</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/></div>{filtered.length===0?<p className="no-history">{t.noHistory}</p>:<div className="history-list">{filtered.map(item=><div className="history-item" key={item.id}><div><b>{item.name||'—'}</b><small>{item.value} · {item.price} {item.currency}</small></div><div className="history-actions"><button onClick={()=>load(item)}>{t.edit}</button><button onClick={()=>{setForm({...defaults,...item});setTimeout(()=>print(),50)}}>{t.reprint}</button><button className="delete" onClick={()=>remove(item.id)}>×</button></div></div>)}</div>}</section></main><footer><span>Barcode Studio · v0.4 · Windows 10 / 11</span><span>تتم الطباعة حسب الطابعة المحددة في نافذة Windows</span></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
